name: CI

on: [push]

jobs:
  build:
    name: Test on VM ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-14]

    steps:
    - uses: actions/checkout@v1
    - name: Run install script
      run: ./install.sh
